### ISSUE TITLE
Improved markdown

### ISSUE THREAD

**Issue by finnbar** [WarwickTabletop/tgrsite#193]
Add improved markdown rendering such that you can specify the classes of things inline. An example could be `![alt text](src)|css|`, although exact syntax is up to the implementer.

Python-Markdown provides this functionality as an extension (https://python-markdown.github.io/extensions/attr_list/), although the use of curly braces may get confused with Django's templating engine. We'll have to investigate.

**Comment by the-Bruce** [comment]
I think I will just add the attr_list to the non-restricted markdown parser. It seems like the most general solution to the problem, and I can make a couple of classes for newsletters that combine the float with some different sizing rules

**Comment by the-Bruce** [comment]
As an aside, it won't affect the templating engine itself, as that isn't ever run over the actual content of anything retrieved from the database (for hopefully obvious security reasons). The only problem is that I was considering a plugin that does look for {{ }} tags to add substitutions into documents, that may get confused. That is, however, a problem for when I get round to doing that.
