### ISSUE TITLE
Dark Mode in Emails

### ISSUE THREAD

**Issue by finnbar** [WarwickTabletop/tgrsite#230]
I've had this requested by Cara. I don't remember how the current dark mode CSS is written (i.e. is there an email-friendly small version), but if so, when emailing out the newsletter we could check the account associated with the email for dark mode settings.

Happy to make this a wontfix if it's too much work.

**Comment by the-Bruce** [comment]
Ooop, just seen this. Probably not easy, I'm afraid. The email system is too friable for me to be confident it will work (besides, its going into an inbox that is otherwise 99% light mode, the benefits are negligible).
