### ISSUE TITLE
Minor Bug: Can't see Embedded Images in PM's

### ISSUE THREAD

**Issue by Professor-JRC** [WarwickTabletop/tgrsite#254]
Just a small noticed thing; when sending a PM and embedding an image, it does not display when looking at the message preview, or in the message itself.

**Comment by finnbar** [comment]
Discussed this with Thomas - the behaviour is _technically correct_ at the moment, but only because image sending was disabled to avoid sending of inappropriate images etc. as messages couldn't be moderated. Messages can now be moderated, and as such we should allow image sending again. Will fix.

**Comment by the-Bruce** [comment]
Fixed in 0e325d08
